name: Python Lint and Format Check

on: 
  pull_request:
  push:

jobs:
  run-python-check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: check out source repository
        uses: actions/checkout@v2

      - name: set up python env
        uses: actions/checkout@v2
        with:
          python-version: "3.10"

      - name: install rye
        shell: bash
        env:
          RYE_INSTALL_OPTION: '--yes'
          RYE_VERSION: 0.44.0
        run: |
          curl -sSf https://rye.astral.sh/get | bash

      - name: setup rye path
        shell: bash
        run: |
          echo "$HOME/.rye/shims" >> $GITHUB_PATH

      - name: set up rye
        run: |
          rye pin 3.10
          rye sync
      
      - name: check lint
        run: rye run ruff check . --output-format=github
      
      - name: check format
        run: rye run ruff format . --check --diff
